name: consumer_pingou_com
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_sticky_header: ^0.6.5
  go_router: ^14.0.1
  intl: ^0.19.0
  mask_text_input_formatter: ^2.9.0
  provider: ^6.1.2
  another_flutter_splash_screen: 1.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/img/
    - assets/img/card-brands/
    - assets/img/products/
  uses-material-design: true
